from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 631)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 631))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 631))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 330, 331, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_A = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_A.sizePolicy().hasHeightForWidth())
        self.pushButton_A.setSizePolicy(sizePolicy)
        self.pushButton_A.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_A.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_A.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_A.setObjectName("pushButton_A")
        self.gridLayout.addWidget(self.pushButton_A, 0, 0, 1, 1)
        self.pushButton_CH = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_CH.sizePolicy().hasHeightForWidth())
        self.pushButton_CH.setSizePolicy(sizePolicy)
        self.pushButton_CH.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_CH.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_CH.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_CH.setObjectName("pushButton_CH")
        self.gridLayout.addWidget(self.pushButton_CH, 4, 0, 1, 1)
        self.pushButton_Z = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Z.sizePolicy().hasHeightForWidth())
        self.pushButton_Z.setSizePolicy(sizePolicy)
        self.pushButton_Z.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_Z.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Z.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Z.setObjectName("pushButton_Z")
        self.gridLayout.addWidget(self.pushButton_Z, 1, 2, 1, 1)
        self.pushButton_I = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_I.sizePolicy().hasHeightForWidth())
        self.pushButton_I.setSizePolicy(sizePolicy)
        self.pushButton_I.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_I.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_I.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_I.setObjectName("pushButton_I")
        self.gridLayout.addWidget(self.pushButton_I, 1, 3, 1, 1)
        self.pushButton_Y = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Y.sizePolicy().hasHeightForWidth())
        self.pushButton_Y.setSizePolicy(sizePolicy)
        self.pushButton_Y.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_Y.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_Y.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_Y.setObjectName("pushButton_Y")
        self.gridLayout.addWidget(self.pushButton_Y, 1, 4, 1, 1)
        self.pushButton_b = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_b.sizePolicy().hasHeightForWidth())
        self.pushButton_b.setSizePolicy(sizePolicy)
        self.pushButton_b.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_b.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_b.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_b.setObjectName("pushButton_b")
        self.gridLayout.addWidget(self.pushButton_b, 4, 5, 1, 1)
        self.pushButton_TS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_TS.sizePolicy().hasHeightForWidth())
        self.pushButton_TS.setSizePolicy(sizePolicy)
        self.pushButton_TS.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_TS.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_TS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_TS.setObjectName("pushButton_TS")
        self.gridLayout.addWidget(self.pushButton_TS, 3, 5, 1, 1)
        self.pushButton_V = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_V.sizePolicy().hasHeightForWidth())
        self.pushButton_V.setSizePolicy(sizePolicy)
        self.pushButton_V.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_V.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_V.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_V.setObjectName("pushButton_V")
        self.gridLayout.addWidget(self.pushButton_V, 0, 2, 1, 1)
        self.pushButton_D = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_D.sizePolicy().hasHeightForWidth())
        self.pushButton_D.setSizePolicy(sizePolicy)
        self.pushButton_D.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_D.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_D.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_D.setObjectName("pushButton_D")
        self.gridLayout.addWidget(self.pushButton_D, 0, 4, 1, 1)
        self.pushButton_R = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_R.sizePolicy().hasHeightForWidth())
        self.pushButton_R.setSizePolicy(sizePolicy)
        self.pushButton_R.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_R.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_R.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_R.setObjectName("pushButton_R")
        self.gridLayout.addWidget(self.pushButton_R, 2, 5, 1, 1)
        self.pushButton_G = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_G.sizePolicy().hasHeightForWidth())
        self.pushButton_G.setSizePolicy(sizePolicy)
        self.pushButton_G.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_G.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_G.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_G.setObjectName("pushButton_G")
        self.gridLayout.addWidget(self.pushButton_G, 0, 3, 1, 1)
        self.pushButton_E = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_E.sizePolicy().hasHeightForWidth())
        self.pushButton_E.setSizePolicy(sizePolicy)
        self.pushButton_E.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_E.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_E.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_E.setObjectName("pushButton_E")
        self.gridLayout.addWidget(self.pushButton_E, 0, 5, 1, 1)
        self.pushButton_B = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_B.sizePolicy().hasHeightForWidth())
        self.pushButton_B.setSizePolicy(sizePolicy)
        self.pushButton_B.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_B.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_B.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_B.setObjectName("pushButton_B")
        self.gridLayout.addWidget(self.pushButton_B, 0, 1, 1, 1)
        self.pushButton_T = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_T.sizePolicy().hasHeightForWidth())
        self.pushButton_T.setSizePolicy(sizePolicy)
        self.pushButton_T.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_T.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_T.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_T.setObjectName("pushButton_T")
        self.gridLayout.addWidget(self.pushButton_T, 3, 1, 1, 1)
        self.pushButton_J = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_J.sizePolicy().hasHeightForWidth())
        self.pushButton_J.setSizePolicy(sizePolicy)
        self.pushButton_J.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_J.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_J.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_J.setObjectName("pushButton_J")
        self.gridLayout.addWidget(self.pushButton_J, 1, 1, 1, 1)
        self.pushButton_P = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_P.sizePolicy().hasHeightForWidth())
        self.pushButton_P.setSizePolicy(sizePolicy)
        self.pushButton_P.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_P.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_P.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_P.setObjectName("pushButton_P")
        self.gridLayout.addWidget(self.pushButton_P, 2, 4, 1, 1)
        self.pushButton_L = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_L.sizePolicy().hasHeightForWidth())
        self.pushButton_L.setSizePolicy(sizePolicy)
        self.pushButton_L.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_L.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_L.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_L.setObjectName("pushButton_L")
        self.gridLayout.addWidget(self.pushButton_L, 2, 0, 1, 1)
        self.pushButton_S = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_S.sizePolicy().hasHeightForWidth())
        self.pushButton_S.setSizePolicy(sizePolicy)
        self.pushButton_S.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_S.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_S.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_S.setObjectName("pushButton_S")
        self.gridLayout.addWidget(self.pushButton_S, 3, 0, 1, 1)
        self.pushButton_JO = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_JO.sizePolicy().hasHeightForWidth())
        self.pushButton_JO.setSizePolicy(sizePolicy)
        self.pushButton_JO.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_JO.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_JO.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_JO.setObjectName("pushButton_JO")
        self.gridLayout.addWidget(self.pushButton_JO, 1, 0, 1, 1)
        self.pushButton_O = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_O.sizePolicy().hasHeightForWidth())
        self.pushButton_O.setSizePolicy(sizePolicy)
        self.pushButton_O.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_O.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_O.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_O.setObjectName("pushButton_O")
        self.gridLayout.addWidget(self.pushButton_O, 2, 3, 1, 1)
        self.pushButton_N = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_N.sizePolicy().hasHeightForWidth())
        self.pushButton_N.setSizePolicy(sizePolicy)
        self.pushButton_N.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_N.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_N.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_N.setObjectName("pushButton_N")
        self.gridLayout.addWidget(self.pushButton_N, 2, 2, 1, 1)
        self.pushButton_K = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_K.sizePolicy().hasHeightForWidth())
        self.pushButton_K.setSizePolicy(sizePolicy)
        self.pushButton_K.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_K.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_K.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_K.setObjectName("pushButton_K")
        self.gridLayout.addWidget(self.pushButton_K, 1, 5, 1, 1)
        self.pushButton_M = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_M.sizePolicy().hasHeightForWidth())
        self.pushButton_M.setSizePolicy(sizePolicy)
        self.pushButton_M.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_M.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_M.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_M.setObjectName("pushButton_M")
        self.gridLayout.addWidget(self.pushButton_M, 2, 1, 1, 1)
        self.pushButton_W = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_W.sizePolicy().hasHeightForWidth())
        self.pushButton_W.setSizePolicy(sizePolicy)
        self.pushButton_W.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_W.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_W.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_W.setObjectName("pushButton_W")
        self.gridLayout.addWidget(self.pushButton_W, 4, 1, 1, 1)
        self.pushButton_b_ = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_b_.sizePolicy().hasHeightForWidth())
        self.pushButton_b_.setSizePolicy(sizePolicy)
        self.pushButton_b_.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_b_.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_b_.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_b_.setObjectName("pushButton_b_")
        self.gridLayout.addWidget(self.pushButton_b_, 4, 3, 1, 1)
        self.pushButton_CHS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_CHS.sizePolicy().hasHeightForWidth())
        self.pushButton_CHS.setSizePolicy(sizePolicy)
        self.pushButton_CHS.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_CHS.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_CHS.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_CHS.setObjectName("pushButton_CHS")
        self.gridLayout.addWidget(self.pushButton_CHS, 4, 2, 1, 1)
        self.pushButton_U = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_U.sizePolicy().hasHeightForWidth())
        self.pushButton_U.setSizePolicy(sizePolicy)
        self.pushButton_U.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_U.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_U.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_U.setObjectName("pushButton_U")
        self.gridLayout.addWidget(self.pushButton_U, 3, 2, 1, 1)
        self.pushButton_F = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_F.sizePolicy().hasHeightForWidth())
        self.pushButton_F.setSizePolicy(sizePolicy)
        self.pushButton_F.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_F.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_F.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_F.setObjectName("pushButton_F")
        self.gridLayout.addWidget(self.pushButton_F, 3, 3, 1, 1)
        self.pushButton_bI = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_bI.sizePolicy().hasHeightForWidth())
        self.pushButton_bI.setSizePolicy(sizePolicy)
        self.pushButton_bI.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_bI.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_bI.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_bI.setObjectName("pushButton_bI")
        self.gridLayout.addWidget(self.pushButton_bI, 4, 4, 1, 1)
        self.pushButton_X = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_X.sizePolicy().hasHeightForWidth())
        self.pushButton_X.setSizePolicy(sizePolicy)
        self.pushButton_X.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_X.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_X.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_X.setObjectName("pushButton_X")
        self.gridLayout.addWidget(self.pushButton_X, 3, 4, 1, 1)
        self.pushButton_EH = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_EH.sizePolicy().hasHeightForWidth())
        self.pushButton_EH.setSizePolicy(sizePolicy)
        self.pushButton_EH.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_EH.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_EH.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_EH.setObjectName("pushButton_EH")
        self.gridLayout.addWidget(self.pushButton_EH, 5, 0, 1, 1)
        self.pushButton_YU = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_YU.sizePolicy().hasHeightForWidth())
        self.pushButton_YU.setSizePolicy(sizePolicy)
        self.pushButton_YU.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_YU.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_YU.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_YU.setObjectName("pushButton_YU")
        self.gridLayout.addWidget(self.pushButton_YU, 5, 1, 1, 1)
        self.pushButton_YA = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_YA.sizePolicy().hasHeightForWidth())
        self.pushButton_YA.setSizePolicy(sizePolicy)
        self.pushButton_YA.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton_YA.setMaximumSize(QtCore.QSize(35, 35))
        self.pushButton_YA.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_YA.setObjectName("pushButton_YA")
        self.gridLayout.addWidget(self.pushButton_YA, 5, 2, 1, 1)
        self.hangmanImage = QtWidgets.QLabel(self.centralwidget)
        self.hangmanImage.setGeometry(QtCore.QRect(700, 210, 301, 381))
        self.hangmanImage.setText("")
        self.hangmanImage.setObjectName("hangmanImage")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(390, 530, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.wordLabel = QtWidgets.QLabel(self.centralwidget)
        self.wordLabel.setGeometry(QtCore.QRect(50, 170, 921, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.wordLabel.setFont(font)
        self.wordLabel.setText("")
        self.wordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wordLabel.setObjectName("wordLabel")
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setGeometry(QtCore.QRect(50, 20, 921, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.infoLabel.setFont(font)
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setObjectName("infoLabel")
        self.win_loseLabel = QtWidgets.QLabel(self.centralwidget)
        self.win_loseLabel.setGeometry(QtCore.QRect(380, 100, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.win_loseLabel.setFont(font)
        self.win_loseLabel.setText("")
        self.win_loseLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.win_loseLabel.setObjectName("win_loseLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Виселица"))
        self.pushButton_A.setText(_translate("MainWindow", "А"))
        self.pushButton_B.setText(_translate("MainWindow", "Б"))
        self.pushButton_V.setText(_translate("MainWindow", "В"))
        self.pushButton_G.setText(_translate("MainWindow", "Г"))
        self.pushButton_D.setText(_translate("MainWindow", "Д"))
        self.pushButton_E.setText(_translate("MainWindow", "Е"))
        self.pushButton_JO.setText(_translate("MainWindow", "Ё"))
        self.pushButton_J.setText(_translate("MainWindow", "Ж"))
        self.pushButton_Z.setText(_translate("MainWindow", "З"))
        self.pushButton_I.setText(_translate("MainWindow", "И"))
        self.pushButton_Y.setText(_translate("MainWindow", "Й"))
        self.pushButton_K.setText(_translate("MainWindow", "К"))
        self.pushButton_L.setText(_translate("MainWindow", "Л"))
        self.pushButton_M.setText(_translate("MainWindow", "М"))
        self.pushButton_N.setText(_translate("MainWindow", "Н"))
        self.pushButton_O.setText(_translate("MainWindow", "О"))
        self.pushButton_P.setText(_translate("MainWindow", "П"))
        self.pushButton_R.setText(_translate("MainWindow", "Р"))
        self.pushButton_S.setText(_translate("MainWindow", "С"))
        self.pushButton_T.setText(_translate("MainWindow", "Т"))
        self.pushButton_U.setText(_translate("MainWindow", "У"))
        self.pushButton_F.setText(_translate("MainWindow", "Ф"))
        self.pushButton_X.setText(_translate("MainWindow", "Х"))
        self.pushButton_TS.setText(_translate("MainWindow", "Ц"))
        self.pushButton_CH.setText(_translate("MainWindow", "Ч"))
        self.pushButton_W.setText(_translate("MainWindow", "Ш"))
        self.pushButton_CHS.setText(_translate("MainWindow", "Щ"))
        self.pushButton_b_.setText(_translate("MainWindow", "Ъ"))
        self.pushButton_bI.setText(_translate("MainWindow", "Ы"))
        self.pushButton_b.setText(_translate("MainWindow", "Ь"))
        self.pushButton_EH.setText(_translate("MainWindow", "Э"))
        self.pushButton_YU.setText(_translate("MainWindow", "Ю"))
        self.pushButton_YA.setText(_translate("MainWindow", "Я"))
        self.playButton.setText(_translate("MainWindow", "Начать попытку"))
        self.infoLabel.setText(_translate("MainWindow", "Добро пожаловать в игру виселица, чтобы начать игру нажмите кнопку \"Начать попытку\"!"))
